### PR TITLE
[WIP] Support marshalling/unmarshalling of discriminators

### LINKED ISSUE #4: Disambiguating between different subclasses
Hi there @sigma, I've started using this great library in https://github.com/ensime/ensime-emacs/pull/673, and ran into a slight issue. Wondering if perhaps you could provide some advice.

Our use-case is mirroring a server-side protocol. We're using the `plist` driver. 

In some of the protocol messages, there are fields that are required to be subtypes of a given type. For example:
```scala
final case class RefactorReq(
  procId: Int,
  params: RefactorDesc,
  interactive: Boolean
)
```

Here, `params` can be one of several messages; we need to disambiguate between them by consing the name of the constructor to the plist; e.g.
```
(:ensime-api-rename-refactor-desc (:new-name "bar" :file "foo.scala" :start 1 :end 100))
```

I'd be happy to add this functionality to the package, but need some guidance on how to approach that. I was thinking that this disambiguation should only be activated if a slot's type is a class marked `:abstract t`.

Any thoughts?

### PR DESCRIPTION
**Pull request by iravid**
Resolves #4.

### CODE REVIEW

**Comment by iravid** [comment]
@sigma The marshalling side should be ready. I've never written something serious in elisp, so I'd appreciate any feedback you have on the approach I've taken.

Thanks! I'll do the unmarshalling side soon-ish.

**Comment by iravid** [comment]
Weird. The tests pass on my installation (emacs 25.3 though). Not sure what's the issue there.

**Comment by iravid** [comment]
We ended up going with a home-grown implementation inspired by your library; thanks for your help!

**Comment by sigma** [comment]
oh that's too bad. I'm still going to try to add an equivalent feature generically, thanks for the idea !

**Comment by iravid** [comment]
@sigma Glad I could give back something :-)

**Pull request closed without merging**
