### PR TITLE
Package fixes

### PR DESCRIPTION
**Pull request by purcell**
I noticed a bunch of byte-compilation warnings at installation time (see https://github.com/purcell/emacs.d/issues/417), so I thought I'd send you a small PR which fixes a number of them... :-)

### CODE REVIEW

**Comment by sigma** [comment]
Hi Steve. thanks for looking into this.

I have done similar things myself (see the `no-warnings` branch), but I'm not sure it's as straightforward as that. In particular it appears there might be subtle differencies between `cl-defmethod` and `defmethod`, which I'm not sure I fully understand or know how to workaround.

At any rate, we should at least make sure the tests are happy about the change :)

**Comment by purcell** [comment]
Well, for a start I was missing the `cl-generic` package dependency. With that, everything but Emacs 25.1 appears okay, at least. Not sure why the built-in `cl-generic` would break things... :-/

**Comment by purcell** [comment]
(Failed job is here: https://travis-ci.org/sigma/marshal.el/jobs/214859743)

**Comment by sigma** [comment]
@purcell yeah that's one of the incompatibilities between `defmethod` and `cl-defmethod`: the former understands `(obj nil)` as a specializer for non-eieio types, while the latter cannot since it has an understanding of specializers for primitive types

**Pull request closed without merging**
